[package]
name = "async-calc-dag"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["fs", "test-util"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
